<a href="https://colab.research.google.com/github/EhsanShakil05/Python-for-Engineers/blob/main/Python_Engineering_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
# Importing NumPy

import numpy as np

print(np.__version__)

2.0.2


In [24]:
# NumPy Array

forces = np.array([100, 200, 300, 400])

print(forces)

[100 200 300 400]


In [25]:
# Vector Operation

areas = np.array([10, 10, 10, 10])

stress = forces / areas

print(stress)

[10. 20. 30. 40.]


In [26]:
# Engineering Example
# Beam Stress Distribution

force = np.array([1000, 2000, 3000, 4000])

area = 0.01

stress = force / area

print(stress)

[100000. 200000. 300000. 400000.]


In [27]:
# Matrix Operation

A = np.array([
    [2,1],
    [1,3]
])

print(A)

# Matrix Addition

B = np.array([
    [1,2],
    [3,4]
])

print(A + B)

# Matrix Multiplication

print(A @ B)

[[2 1]
 [1 3]]
[[3 3]
 [4 7]]
[[ 5  8]
 [10 14]]


In [28]:
# Solving Linear Equations
# 2x + y = 5
# x + 3y = 6

A = np.array([
    [2,1],
    [1,3]
])

B = np.array([5,6])

X = np.linalg.solve(A,B)

print(X)

[1.8 1.4]


In [29]:
# Engineering Mini Project

# Spring Calculator
# F = kx

k = 500

x = np.array([0.01,0.02,0.03,0.04])

F = k*x

print(F)

[ 5. 10. 15. 20.]


In [30]:
# Numerical Methods Connection

x = np.linspace(0,3,100)

f = x**3 - x - 2

print(f)

[-2.         -2.0302752  -2.06038345 -2.09015778 -2.11943123 -2.14803684
 -2.17580766 -2.20257673 -2.22817709 -2.25244177 -2.27520383 -2.2962963
 -2.31555222 -2.33280463 -2.34788658 -2.3606311  -2.37087125 -2.37844005
 -2.38317055 -2.38489579 -2.38344881 -2.37866266 -2.37037037 -2.35840499
 -2.34259955 -2.3227871  -2.29880068 -2.27047333 -2.23763809 -2.200128
 -2.15777611 -2.11041545 -2.05787907 -2.         -1.93661129 -1.86754598
 -1.79263711 -1.71171773 -1.62462086 -1.53117956 -1.43122687 -1.32459582
 -1.21111946 -1.09063083 -0.96296296 -0.82794891 -0.68542171 -0.5352144
 -0.37716003 -0.21109163 -0.03684225  0.14575507  0.3368673   0.53666138
  0.74530428  0.96296296  1.18980438  1.42599549  1.67170326  1.92709464
  2.19233659  2.46759607  2.75304004  3.04883546  3.35514929  3.67214848
  4.          4.3388708   4.68892785  5.05033809  5.4232685   5.80788602
  6.20435763  6.61285027  7.0335309   7.46656649  7.91212399  8.37037037
  8.84147258  9.32559757  9.82291232 10.33358377 10.857